apiVersion: v2
name: juicefs-stack
description: Shared JuiceFS CSI driver and Redis setup
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: redis
    version: 18.1.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: juicefs-csi-driver
    version: 0.23.1
    repository: https://juicedata.github.io/charts/
    condition: juicefs.csi.enabled
