juicefs-csi-driver:
  storageClass:
    enabled: true
  controller:
    enabled: true
  node:
    enabled: true
  juicefs:
    configFromSecret: juicefs-csi-config

juicefs:
  csi:
    enabled: true
    storageClass:
      create: true
      name: juicefs-sc
    runtimeProvision: true
  redis:
    servicename: redis-jfs
    port: 6379
    password: ""
    db: 1

