apiVersion: v1
kind: Secret
metadata:
  name: juicefs-csi-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "juicefs-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  metaurl: "redis://:{{ .Values.redis.auth.password }}@{{ .Values.redis.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.juicefs.meta.port }}/{{ .Values.juicefs.meta.db }}"
