apiVersion: v1
kind: Secret
metadata:
  name: juicefs-csi-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "juicefs-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  metaurl: "redis://:{{ .Values.juicefs.redis.password }}@{{ .Values.juicefs.redis.servicename }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.juicefs.redis.port }}/{{ .Values.juicefs.redis.db }}"
