name: Helm Unit Tests and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Lint Helm chart
        run: helm lint .

      - name: Run unit tests
        run: helm unittest .
